### ISSUE TITLE
`sl-exporter` should be open sourced (and archive Half-life)

### ISSUE THREAD

**Issue by DavidNix** [strangelove-ventures/sl-exporter#21]
Once we feel like sl-exporter is good for an MVP release. I suggest open-sourcing it and archive half-life. 

It's rare we get feature or support requests for half-life. However, one less project to maintain is a win for SL. Additionally, half-life is not a good solution at scale, and I would not want to encourage teams to use it if they are monitoring more than a handful of nodes.

**Comment by jonathanpberger** [comment]
Put under apache in https://github.com/strangelove-ventures/sl-exporter/commit/971769497c0b836d3bb6103a1d10b831a6e30ca2. Closing ticket.
